import = [
  # "~/.config/alacritty/themes/themes/nightfox.toml",
     "~/.config/alacritty/themes/themes/totokyo-night-storm.tom",
]

[font]
normal.family = "JetBrains Mono Nerd Font"
bold.family = "JetBrains Mono Nerd Font"
size = 11
# draw_bold_text_with_bright_colors = true

[window]
opacity = 0.9
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 500
lines = 200

[shell]
program = "/bin/fish"
#args = ["-l"]

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
#{ key = "A", chars = "ctrl" },
{ key = "F11", action = "ToggleFullscreen"},
]
